server:
  port: 8090
  servlet:
    context-path: /ui
security:
  oauth2:
    client:
      clientId: userservice3
      clientSecret: 123456
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      scope: FOO
    resource:
      jwt:
        key-value: 123456789
spring:
  thymeleaf:
    cache: false

#logging:
#  level:
#    ROOT: DEBUG